# Generated by Django 3.2.4 on 2021-11-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210926_1152'),
        ('users', '0003_auto_20210926_1200'),
    ]

    operations = [
    ]
