# Generated by Django 3.2 on 2022-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220110_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approve_Wholesaler_or_Retailer',
            field=models.CharField(choices=[('Approve as Wholesaler', 'approveWholesaler'), ('Approve as Retailer', 'approveRetailer')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Wholesaler', 'Wholesaler'), ('Retailer', 'Retailer')], default='Normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_website',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
