# Generated by Django 3.2 on 2022-01-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220110_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='approve_Wholesaler_or_Retailer',
            field=models.CharField(choices=[('Approve as Wholesaler', 'approveWholesaler'), ('Approve as Retailer', 'approveRetailer')], default=None, max_length=30),
        ),
    ]
