# Generated by Django 3.2 on 2022-01-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_approve_wholesaler_or_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='approve_Wholesaler_or_Retailer',
            field=models.CharField(choices=[('None', 'None'), ('Approve as Wholesaler', 'approveWholesaler'), ('Approve as Retailer', 'approveRetailer')], default='None', max_length=30),
        ),
    ]
