# Generated by Django 3.2 on 2022-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_approve_wholesaler_or_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='approve_Wholesaler_or_Retailer',
        ),
        migrations.AddField(
            model_name='profile',
            name='approveRetailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='approveWholesaler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
