# Generated by Django 3.1.1 on 2021-09-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('content', models.TextField(max_length=4000)),
            ],
            options={
                'verbose_name_plural': 'Privacy Policies',
            },
        ),
    ]
