# Generated by Django 3.2.4 on 2021-12-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_exchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'verbose_name_plural': 'Return Policies'},
        ),
    ]
