# Generated by Django 3.2 on 2022-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20220119_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='oulet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
