# Generated by Django 3.2 on 2022-01-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_contact_oulet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='oulet',
            new_name='outlet',
        ),
    ]
