# Generated by Django 3.1.1 on 2021-09-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300)),
                ('vacancy_number', models.IntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
