# Generated by Django 3.2 on 2021-12-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_vacancy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField()),
                ('cv', models.FileField(upload_to='')),
                ('cover_letter', models.FileField(upload_to='')),
                ('hear', models.CharField(max_length=255)),
                ('refer', models.CharField(max_length=255)),
                ('next_role', models.CharField(max_length=255)),
                ('offer', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('opening', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('experiance', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='get_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.job'),
        ),
    ]
