# Generated by Django 3.2 on 2022-01-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_auto_20211230_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='cover_letter',
            field=models.FileField(upload_to='vacancy/coverletter'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='cv',
            field=models.FileField(upload_to='vacancy/cv'),
        ),
    ]
