# Generated by Django 3.2 on 2022-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211229_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilememory',
            name='retailprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mobilememory',
            name='wholesaleprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
