# Generated by Django 3.2 on 2022-01-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220111_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdeals',
            name='retail_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
