# Generated by Django 3.2 on 2022-01-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_specialdeals_retail_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdeals',
            name='size',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mobilememory'),
        ),
        migrations.AlterField(
            model_name='specialdeals',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='specialdeals',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='specialdeals',
            name='retail_discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
