# Generated by Django 3.2 on 2022-01-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_subcategory_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdeals',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
