# Generated by Django 3.2 on 2022-01-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_specialdeals_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialdeals',
            old_name='size',
            new_name='productsize',
        ),
        migrations.AlterField(
            model_name='specialdeals',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
