# Generated by Django 3.2 on 2022-01-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220114_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdeals',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='specialdeals',
            name='productsize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mobilememory'),
        ),
    ]
