# Generated by Django 3.2 on 2022-01-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220114_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificcategory',
            name='specific_category',
            field=models.CharField(max_length=50),
        ),
    ]
