# Generated by Django 3.2 on 2022-01-16 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_specificcategory_specific_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdeals',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.CreateModel(
            name='Specialdealattr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('retail_discount_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('productsize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mobilememory')),
                ('specialdeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.specialdeals')),
            ],
            options={
                'verbose_name_plural': 'Special Deal Attr',
            },
        ),
    ]
