# Generated by Django 3.2 on 2022-01-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220116_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='Add_features',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
